# Generated by Django 4.2.17 on 2024-12-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=1, help_text='№ на тема: 1, 2, ... 18', verbose_name='Тема №')),
                ('title', models.TextField(help_text='Заглавие на темата', verbose_name='Заглавие')),
                ('remark', models.TextField(blank=True, help_text='Допълнително указание или коментар към темата', verbose_name='Коментар/забележка')),
                ('tasks_total', models.PositiveSmallIntegerField(default=24, help_text='Максимален брой задачи', verbose_name='Общ брой задачи')),
                ('tasks_knowledge', models.PositiveSmallIntegerField(default=0, help_text='Знание - брой задачи ', verbose_name='Знание')),
                ('tasks_comprehension', models.PositiveSmallIntegerField(default=0, help_text='Разбиране - брой задачи ', verbose_name='Разбиране')),
                ('tasks_application', models.PositiveSmallIntegerField(default=0, help_text='Приложение - брой задачи ', verbose_name='Приложение')),
                ('tasks_analysis', models.PositiveSmallIntegerField(default=0, help_text='Анализ - брой задачи ', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Теми',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пофил на потребител', 'verbose_name_plural': 'Пофили на потребител'},
        ),
        migrations.CreateModel(
            name='ThemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveSmallIntegerField(default=1, help_text='№ на точка в темата: 1, 2, ... ', verbose_name='Точка №')),
                ('title', models.TextField(help_text='Заглавие на точката', verbose_name='Заглавие')),
                ('criterion', models.TextField(help_text='Критерий за оценяване. За темата - забележка', verbose_name='Заглавие')),
                ('total_points', models.PositiveSmallIntegerField(default=20, help_text='Максимален брой точки', verbose_name='Точки max')),
                ('knowledge', models.PositiveSmallIntegerField(default=0, help_text='Знание - брой задачи ', verbose_name='Знание')),
                ('comprehension', models.PositiveSmallIntegerField(default=0, help_text='Разбиране - брой задачи ', verbose_name='Разбиране')),
                ('application', models.PositiveSmallIntegerField(default=0, help_text='Приложение - брой задачи ', verbose_name='Приложение')),
                ('analysis', models.PositiveSmallIntegerField(default=0, help_text='Анализ - брой задачи ', verbose_name='Анализ')),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.theme')),
            ],
            options={
                'verbose_name': 'Тема - точка',
                'verbose_name_plural': 'Теми - точки',
            },
        ),
    ]
