# Generated by Django 4.2.17 on 2024-12-29 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Специалност',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='main.school', verbose_name='училище'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciality',
            field=models.ForeignKey(help_text='специалност по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_speciality', to='main.specialty', verbose_name='Специалност'),
        ),
        migrations.AlterField(
            model_name='school',
            name='specialities',
            field=models.ManyToManyField(to='main.specialty', verbose_name='Специалности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session_theme',
            field=models.PositiveSmallIntegerField(default=1, help_text='номер на тема от НИП по подразбиране', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Тема'),
        ),
    ]
