# Generated by Django 4.2.17 on 2024-12-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_theme_alter_userprofile_options_themeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=0, help_text='генерира се автоматично')),
                ('text', models.TextField(blank=True, default='', help_text='Формулировка (текст) на въпроса', verbose_name='Въпрос')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'затворен тип без картинка'), (2, 'затворен тип с картинка'), (3, 'съпоставяне ляво --> дясно'), (4, 'съпоставяне картинка --> опции'), (5, 'отворен отговор')], default=1, help_text='тип на въпроса')),
                ('picture', models.ImageField(blank=True, upload_to='task_pics', verbose_name='Картинка')),
                ('group', models.PositiveSmallIntegerField(default=0, help_text='0 - ако не е групирано')),
                ('mark_red', models.BooleanField(default=False, null=True, verbose_name='Червен маркер')),
                ('mark_green', models.BooleanField(default=False, null=True, verbose_name='Зелен маркер')),
                ('mark_yellow', models.BooleanField(default=False, null=True, verbose_name='Жълт маркер')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_knowledge', to='main.themeitem')),
            ],
            options={
                'verbose_name': 'Въпрос',
                'verbose_name_plural': 'Въпроси',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leading_char', models.CharField(blank=True, default='', help_text='№ или буква', max_length=4, verbose_name='Водещ символ')),
                ('text', models.CharField(blank=True, default='', help_text='Формулировка (текст) на опцията(отговора)', max_length=200, verbose_name='Текст')),
                ('value', models.CharField(blank=True, default='', help_text='Отговор - стойност', max_length=20, verbose_name='Стойност')),
                ('value_name', models.CharField(blank=True, default='', help_text='Отговор - име', max_length=200, verbose_name='Стойност - име')),
                ('checked', models.BooleanField(help_text='Отговор за опции с маркиране', null=True, verbose_name='Отговор - маркирано')),
                ('checked_t', models.BooleanField(help_text='генерира се автоматично', null=True, verbose_name='Отговор - маркирано')),
                ('value_t', models.CharField(blank=True, default='', help_text='генерира се автоматично', max_length=20, verbose_name='Стойност')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.task')),
            ],
            options={
                'verbose_name': 'Въпрос - опция',
                'verbose_name_plural': 'Въпроси - опции',
            },
        ),
    ]
