# Generated by Django 4.2.17 on 2025-01-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userprofile_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, height_field=110, upload_to='sys_pics', verbose_name='Лого', width_field=110),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(choices=[(True, 'мъж'), (False, 'жена')], default=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='school',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='main.specialty', verbose_name='Специалности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Системен администратор'), (2, 'НАБЛЮДАВАЩ АДМИНИСТРАТОР'), (3, 'УЧИЛИЩЕН АДМИНИСТРАТОР'), (4, 'УЧИТЕЛ'), (5, 'УЧЕНИК')], default=5, help_text='роля (ниво на достъп)', verbose_name='Роля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='main.school', verbose_name='училище'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speciality',
            field=models.ForeignKey(blank=True, help_text='специалност по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_speciality', to='main.specialty', verbose_name='Специалност'),
        ),
    ]
