# Generated by Django 4.2.17 on 2024-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_taskitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', help_text='Съкратено име на училището', max_length=20, verbose_name='Абревиатура')),
                ('full_name', models.TextField(blank=True, default='', help_text='Пълно име на училището', verbose_name='Име')),
                ('city', models.CharField(blank=True, default='', help_text='Населено място, където се намира училището', max_length=50, verbose_name='Населено място')),
                ('address', models.CharField(blank=True, default='', help_text='Адрес в населеното място (ул. ... №...)', max_length=50, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=35, verbose_name='e-mail')),
                ('boss', models.CharField(blank=True, default='', help_text='Име на директора на училището', max_length=50, verbose_name='Директор')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='themes',
            field=models.ManyToManyField(blank=True, to='main.theme'),
        ),
    ]
