# Generated by Django 4.2.17 on 2025-01-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_school_logo_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to='sys_pics', verbose_name='Лого'),
        ),
    ]
