# Generated by Django 4.2.17 on 2025-02-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_school_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='remark',
        ),
        migrations.AddField(
            model_name='theme',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.specialty'),
            preserve_default=False,
        ),
    ]
