# Generated by Django 4.2.17 on 2024-12-28 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_school_task_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='id на потрбител')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='име на потрбител')),
                ('action', models.CharField(default='', max_length=200, verbose_name='Действие')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата и час')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Училище/организация', 'verbose_name_plural': 'Училища/организации'},
        ),
    ]
