# Generated by Django 4.2.17 on 2025-02-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_theme_remark_theme_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mark_green',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mark_red',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mark_yellow',
        ),
        migrations.RemoveField(
            model_name='task',
            name='themes',
        ),
    ]
