# Generated by Django 4.2.17 on 2024-12-29 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_log_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Име')),
                ('attachment', models.FileField(upload_to='docs/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_field_num', models.CharField(blank=True, default='', max_length=3, verbose_name='Професионално направление - номер')),
                ('professional_field_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Професионално направление - име')),
                ('profession_num', models.CharField(blank=True, default='', max_length=6, verbose_name='Професия - номер')),
                ('profession_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Професия - име')),
                ('specialty_num', models.CharField(blank=True, default='', max_length=8, verbose_name='Специалност - номер')),
                ('specialty_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Специалност - име')),
                ('nip', models.FileField(upload_to='docs/', verbose_name='НИП')),
            ],
            options={
                'verbose_name': 'Специалност',
                'verbose_name_plural': 'Специалности',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'знание'), (2, 'разбиране'), (3, 'приложение'), (4, 'анализ')], default=1, help_text='ниво на въпроса по Блум'),
        ),
        migrations.AddField(
            model_name='task',
            name='school',
            field=models.ManyToManyField(blank=True, to='main.school', verbose_name='id на училище в което се ползва'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'тъмна'), (2, 'светла')], default=5, help_text='роля (ниво на достъп)', verbose_name='Роля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='main.school'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_screen',
            field=models.PositiveSmallIntegerField(choices=[(1, 'тъмна'), (2, 'светла')], default=1, help_text='цветова схема на интерфейса', verbose_name='Интерфейс'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_theme',
            field=models.PositiveSmallIntegerField(default=1, help_text='номер на тема от НИП по подразбиране', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и час'),
        ),
        migrations.AddField(
            model_name='school',
            name='specialities',
            field=models.ManyToManyField(to='main.specialty', verbose_name='Езиково обучение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Специалност',
            field=models.ForeignKey(help_text='специалност по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_speciality', to='main.specialty'),
        ),
    ]
