# Generated by Django 4.2.17 on 2025-02-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='num',
        ),
    ]
