# Generated by Django 4.2.17 on 2025-02-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_task_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='id на потрбител')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='id на потрбител')),
                ('theme', models.PositiveSmallIntegerField(default=0, verbose_name='номер на тема')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='получени точки')),
                ('time', models.IntegerField(default=0, verbose_name='продължителност')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата и час')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тестове',
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='id на потребител'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='име на потребител'),
        ),
    ]
