# Generated by Django 4.2.17 on 2025-02-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test_alter_log_user_id_alter_log_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='textWrap',
            field=models.CharField(blank=True, default='s', help_text='Разположение на текста спрямо картинката (e,w,n,s)', max_length=1, verbose_name='Разположение на текста'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.themeitem'),
        ),
    ]
