# Generated by Django 4.2.17 on 2025-02-18 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_task_textwrap_alter_task_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='id на потребител')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='име на потребител')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и час')),
                ('text', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='main.task')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментари',
            },
        ),
    ]
