# Generated by Django 4.2.17 on 2025-02-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Общ текстов контекст за въпросите', verbose_name='Контекст')),
                ('picture', models.ImageField(blank=True, help_text='Обща картинка за въпросите', null=True, upload_to='context_pics', verbose_name='Картинка')),
                ('textWrap', models.CharField(blank=True, default='s', help_text='Разположение на текста спрямо картинката (e,w,n,s)', max_length=1, verbose_name='Разположение на текста')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.ForeignKey(blank=True, help_text='Контекст за въпроса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.taskcontext'),
        ),
    ]
