# Generated by Django 4.2.17 on 2025-02-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_taskcontext_task_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontext',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
    ]
