# Generated by Django 4.2.17 on 2025-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_taskcontext_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcontext',
            options={'verbose_name': 'Контекст', 'verbose_name_plural': 'Контексти'},
        ),
        migrations.AddField(
            model_name='task',
            name='stat_attempts',
            field=models.IntegerField(default=0, help_text='колко пъти е изтеглен въпроса', verbose_name='Брой опити'),
        ),
        migrations.AddField(
            model_name='task',
            name='stat_points',
            field=models.FloatField(default=0, help_text='колко точки общо е получено от отговори', verbose_name='Получени точки'),
        ),
    ]
