# Generated by Django 4.2.17 on 2025-03-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_taskcontext_options_task_stat_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user_name',
        ),
        migrations.AddField(
            model_name='test',
            name='spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.specialty', verbose_name='специалност'),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='потребител'),
        ),
        migrations.AlterField(
            model_name='test',
            name='points',
            field=models.IntegerField(default=0, verbose_name='получени точки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.theme', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.CharField(default='00:00:00', max_length=10, verbose_name='продължителност'),
        ),
    ]
