# Generated by Django 4.2.17 on 2025-05-03 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_testresult_delete_test_answer_test_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='text',
            field=models.CharField(blank=True, default='', help_text='Формулировка (текст) на опцията(отговора)', max_length=400, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='value_name',
            field=models.CharField(blank=True, default='', help_text='Отговор - име', max_length=400, verbose_name='Стойност - име'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и час'),
        ),
    ]
