# Generated by Django 4.2.17 on 2025-05-05 20:07

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_taskitem_text_alter_taskitem_value_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to=main.models.school_pic_path, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, upload_to=main.models.task_pic_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='taskcontext',
            name='picture',
            field=models.ImageField(blank=True, help_text='Обща картинка за въпросите', null=True, upload_to=main.models.context_pic_path, verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_file', models.FileField(help_text='MS Word файл с теста', upload_to=main.models.generated_test_path, verbose_name='Тест файл')),
                ('answer_key_file', models.FileField(help_text='MS Word файл с ключа за теста', upload_to=main.models.answer_key_path, verbose_name='Ключ за теста')),
                ('generation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата на генериране')),
                ('is_marked', models.BooleanField(default=False, help_text='Дали тестът е маркиран или не', verbose_name='Маркиран')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tests', to='main.school', verbose_name='Училище')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tests', to='main.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Генериран тест',
                'verbose_name_plural': 'Генерирани тестове',
                'ordering': ['-generation_date'],
            },
        ),
    ]
