# Generated by Django 4.2.17 on 2025-05-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_school_logo_alter_task_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtest',
            name='is_marked',
        ),
    ]
