# Generated by Django 4.2.17 on 2025-05-08 22:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_generatedtest_is_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Име на шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to=main.models.template_file_path, verbose_name='Файл на шаблона')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на качване')),
            ],
        ),
        migrations.AddField(
            model_name='specialty',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'втора'), (3, 'трета')], default=3, help_text='Степен на професионална квалификация'),
        ),
    ]
